package com.runner;


import java.io.File;
import java.util.ArrayList;
import java.util.List;

import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;

public class JVMReport {
	public static void generateJVMReport(String jsonLoc) {
	   
		File jvmPath = new File("C:\\Users\\rv\\eclipse-workspace\\Day1_Cucumbe_R\\target");
		List<String>li = new ArrayList<String>();
		li.add(jsonLoc);
		
		Configuration con =new Configuration(jvmPath, "Facebook Report");
		con.addClassifications("OS","Windows");
		con.addClassifications("Browser", "Chrome Browser");
		con.addClassifications("version", "Above 90");
		con.addClassifications("Generated by", "vicky");
		
		
		ReportBuilder builder = new ReportBuilder(li, con);
		builder.generateReports();
		
	}

}
